{% if salt_version.startswith('2018') %}
FROM python:2.7-alpine
{% else %}
FROM python:3.7-alpine
{% endif %}

RUN apk add --no-cache gcc g++ autoconf make libffi-dev openssl-dev dumb-init

RUN addgroup -g 450 -S salt && adduser -s /bin/sh -SD -G salt salt && \
    mkdir -p /etc/pki /etc/salt/pki /etc/salt/minion.d/ /etc/salt/master.d /etc/salt/proxy.d /var/cache/salt /var/log/salt /var/run/salt && \
    chmod -R 2775 /etc/pki /etc/salt /var/cache/salt /var/log/salt /var/run/salt && \ 
    chgrp -R salt /etc/pki /etc/salt /var/cache/salt /var/log/salt /var/run/salt

ENTRYPOINT ["/usr/bin/dumb-init"]
{% if salt_version.startswith('2018') %}
ADD saltinit2.sh /usr/local/bin/saltinit2.sh
CMD ["/usr/local/bin/saltinit2.sh"]
{% else %}
ADD saltinit.py /usr/local/bin/saltinit
CMD ["/usr/local/bin/saltinit"]
{% endif %}

EXPOSE 4505 4506 8000
# VOLUME /etc/salt/pki/

{% if salt_version.startswith('2018') %}
RUN pip install --no-cache-dir salt=={{salt_version}} pycryptodomex CherryPy pyOpenSSL 'msgpack<1.0' 'slackclient<2.0' boto3 boto
{% else %}
RUN pip3 install --no-cache-dir salt=={{salt_version}} pycryptodomex CherryPy pyOpenSSL slackclient boto3 boto
{% endif %}

RUN su - salt -c 'salt-run salt.cmd tls.create_self_signed_cert'
